# Generated by Django 4.0.4 on 2022-06-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_reputation_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reputation',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
