# Generated by Django 4.0.3 on 2022-04-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('UP', 'Upper Pokomo'), ('LP', 'Malanchini')], max_length=50)),
                ('word', models.CharField(max_length=150)),
                ('defination', models.TextField()),
                ('example', models.TextField()),
                ('other_definations', models.TextField()),
            ],
        ),
    ]
