# Generated by Django 4.0.4 on 2022-06-22 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Upper Pokomo', 'Upper Pokomo'), ('Malanchini', 'Malanchini')], max_length=50)),
                ('clan', models.CharField(choices=[('Ndera', 'Ndera'), ('Zubaki', 'Zubaki'), ('Kinakomba', 'Kinakomba'), ('Gwano', 'Gwano'), ('Malanchini', 'Malanchini'), ('None', 'None')], max_length=50)),
                ('word', models.CharField(max_length=150, unique=True)),
                ('definition', models.TextField()),
                ('example', models.TextField()),
                ('other_definitions', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('downvote', models.ManyToManyField(blank=True, related_name='termDownVotes', to=settings.AUTH_USER_MODEL)),
                ('upvote', models.ManyToManyField(blank=True, related_name='termUpVotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.term')),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Wrong definition', 'Wrong definition'), ('Hate speech', 'Hate speech'), ('Other', 'Other')], max_length=100)),
                ('other_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagger', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.term')),
            ],
        ),
    ]
