# Generated by Django 4.0.3 on 2022-04-21 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0002_term_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='term',
            name='approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='term',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='term',
            name='downvote',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='upvote',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='language',
            field=models.CharField(choices=[('Upper Pokomo', 'Upper Pokomo'), ('Malanchini', 'Malanchini')], max_length=50),
        ),
        migrations.AlterField(
            model_name='term',
            name='other_definations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('wrong definition', 'wrong definition'), ('hate speech', 'hate speech'), ('other', 'other')], max_length=100)),
                ('other_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.term')),
            ],
        ),
    ]
