# Generated by Django 4.0.3 on 2022-04-21 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_rename_user_term_author_term_approval_term_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='approval',
            new_name='approved',
        ),
    ]
