# Generated by Django 4.0.3 on 2022-05-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_rename_defination_term_definition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='clan',
            field=models.CharField(choices=[('Ndera', 'Ndera'), ('Zubaki', 'Zubaki'), ('Kinakomba', 'Kinakomba'), ('Gwano', 'Gwano'), ('Malanchini', 'Malanchini'), ('None', 'None')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='term',
            name='word',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
