# Generated by Django 4.0.3 on 2022-05-15 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0006_term_clan_alter_term_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='term',
            name='upvote',
        ),
        migrations.AlterField(
            model_name='flag',
            name='flagged_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.IntegerField(blank=True, default=0, null=True)),
                ('downvote', models.IntegerField(blank=True, default=0, null=True)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.term')),
            ],
        ),
    ]
