# Generated by Django 4.0.3 on 2022-05-15 22:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0007_remove_term_downvote_remove_term_upvote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='upvote',
        ),
        migrations.AddField(
            model_name='term',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='termDownVotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='term',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='termUpVotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
