# Generated by Django 4.0.4 on 2022-05-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_remove_vote_downvote_remove_vote_upvote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='reason',
            field=models.CharField(choices=[('Wrong definition', 'Wrong definition'), ('Hate speech', 'Hate speech'), ('Other', 'Other')], max_length=100),
        ),
    ]
